library(harmony)
library(Seurat) 
library(ggpubr) 
library(dplyr)
library(ggplot2) 
library(cowplot) 
library(RColorBrewer) 
library(corrplot) 
library(data.table)
library(Signac)
library(scCustomize)
set.seed(1234)
subset_3 <- readRDS("ATAC_integrated.rds")
fa <- Rsamtools::FaFile("chromosome_w8.fasta")
subset_3 <- RegionStats(subset_3, genome = fa, assay='peaks')
subset_3 <- LinkPeaks(
  object = subset_3,
  peak.assay = "peaks",
  expression.assay = "RNA")
saveRDS(subset_3, "ATAC_integrated_with_links.rds")
