library(Seurat)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(dplyr)
library(RColorBrewer)
library(corrplot)
data.filt <- readRDS("data_integrated_harmony_DUBStepR_2.rds")
library(SeuratDisk)
SaveH5Seurat(data.filt, filename = "data_integrated_harmony_DUBStepR_2.h5Seurat")
Convert("data_integrated_harmony_DUBStepR_2.h5Seurat", dest = "h5ad")
