library(Seurat)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(dplyr)
library(RColorBrewer)
library(corrplot)
data.filt <- readRDS("data_integrated_ATAC_DUBStepR.rds")
library(scrattch.io)
write_dgCMatrix_csv(data.filt@assays$ATAC@counts, "ATAC_counts_DUBStep.csv")
