library(Seurat)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(dplyr)
library(RColorBrewer)
library(corrplot)
data.filt <- readRDS("data_integrated_harmony_DUBStepR_3_2.rds")
library(scrattch.io)
write_dgCMatrix_csv(data.filt@assays$RNA@data, "normalized_expression_DUBStepR_3_2.csv")
