library(Seurat) 
library(ggpubr) 
library(dplyr)
library(ggplot2) 
library(cowplot) 
library(RColorBrewer) 
library(corrplot) 
library(data.table)
library(Signac)
library(scCustomize)
library(purrr)
library(tidyverse)
set.seed(1234)
data <- readRDS("data_integrated_ATAC_DUBStepR.rds")
pdf("stats_ATAC.pdf")
VlnPlot(data, features = c("nFeature_ATAC","nCount_ATAC"), pt.size=0)
dev.off()
