library(Seurat) 
library(ggpubr) 
library(dplyr)
library(ggplot2) 
library(cowplot) 
library(RColorBrewer) 
library(corrplot) 
library(data.table)
library(Signac)
library(scCustomize)
library(purrr)
library(tidyverse)
set.seed(1234)
data <- readRDS("data_integrated_harmony_DUBStepR_2.rds")
pdf("stats_RNA.pdf")
VlnPlot(data, features = c("nFeature_RNA","nCount_RNA"), pt.size=0)
dev.off()
