library(Seurat) 
library(ggpubr) 
library(dplyr)
library(ggplot2) 
library(cowplot) 
library(RColorBrewer) 
library(corrplot) 
library(data.table)
library(Signac)
library(scCustomize)
library(purrr)
library(tidyverse)
set.seed(1234)
data <- readRDS("data_integrated_ATAC_DUBStepR_3_2.rds")
new.cluster.ids <- c("Follicle cells","Germ cells A","Ovarian muscle cells","Escort cells","Tracheal cells","Prefollicle cells","Germ cells B")
names(new.cluster.ids) <- levels(data)
data <- RenameIdents(data, new.cluster.ids)
data$seurat_clusters <- Idents(data)
#levels(data) <- sort(levels(data)) 
levels(data) <- c("Ovarian muscle cells","Follicle cells","Tracheal cells","Prefollicle cells","Escort cells","Germ cells A","Germ cells B")
#my_cols <- c('Follicle cells B'='#F68282','Early Germline cells'='#31C53F','Ovarian muscle cells'='#1FA195','Follicle cells A/Escort cells'='#B95FBB','Tracheal cells'='#D4D915','Prefollicle cells'='#28CECA','Late Germline cells'='#ff9a36')
#my_cols <- c('Follicle cells'='#cab2d6','Germ cells A'='#e31a1c','Ovarian muscle cells'='#b15928','Escort cells'='#6a3d9a','Tracheal cells'='#fdbf6f','Prefollicle cells'='#ffff99','Germ cells B'='#ff7f00')
#c0b7c4
my_cols <- c('Follicle cells'='#c0b7c4','Germ cells A'='#e31a1c','Ovarian muscle cells'='#c0b7c4','Escort cells'='#c0b7c4','Tracheal cells'='#c0b7c4','Prefollicle cells'='#c0b7c4','Germ cells B'='#ff7f00')

#my_cols <- c('Follicle cells B'='#cab2d6','Early Germline cells'='#e31a1c','Ovarian muscle cells'='#b15928','Follicle cells A/Escort cells'='#6a3d9a','Tracheal cells'='#fdbf6f','Prefollicle cells'='#ffff99','Late Germline cells'='#ff7f00')
#1f78b4
#subset_3 <- subset(x = data, subset = replicates == "replicate_3")
#subset_4 <- subset(x = data, subset = replicates == "replicate_4")
my_cols2 <- my_cols[order(as.integer(names(my_cols)))]
scales::show_col(my_cols2)
pdf("stats_ATAC_renamed_ordered.pdf",width=6,height=4.5)
#VlnPlot(data, features = c("nFeature_ATAC","nCount_ATAC"), pt.size=0)
p1 <- VlnPlot(data, features = c("nCount_RNA"),cols = my_cols2, pt.size=0)+ theme(axis.text.x = element_text(angle = 60, hjust=1))+ theme(legend.position = 'none')
p2 <- VlnPlot(data, features = c("nCount_ATAC"),cols = my_cols2, pt.size=0)+ theme(axis.text.x = element_text(angle = 60, hjust=1))+ theme(legend.position = 'none')
#p1 + p2
cowplot::plot_grid(p1, p2)
#VlnPlot(subset_3, features = c("nFeature_ATAC","nCount_ATAC"),split.by='replicates', pt.size=0)
#VlnPlot(subset_4, features = c("nFeature_ATAC","nCount_ATAC"),split.by='replicates', pt.size=0)
dev.off()
